Repository taylorjohnson141/identity-maker, pull requests merged in 2020-11, with the labels that each got.

#26 Header eb
  public/index.html
  src/Images/spyIcon.png
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/Header.test.js
Labels: css, testing

#27 Form component tj
  package-lock.json
  package.json
  src/actions/index.js
  src/components/IDForm/IDForm.js
  src/reducers/AddIDReducer.js
Labels: react, redux

#28 Form updates eb
  src/actions/index.js
  src/components/IDForm/IDForm.js
  src/components/IDPage/IDPage.js
  src/reducers/AddIDReducer.js
  src/reducers/index.js
  src/reducers/setCountriesReducer.js
  src/thunks/fetchCountries.js
Labels: enhancement, redux

#29 Identity area tj
  src/components/App/App.js
  src/components/IDArea/IDArea.js
  src/components/IDPage/IDPage.js
  src/components/Identity/Identity.js
  src/components/MissionArea/MissionArea.js
  src/components/StoryArea/StoryArea.js
Labels: react, redux

#35 Story area mission area styles
  public/index.html
  src/components/IDPage/IDPage.js
  src/components/MissionArea/MissionArea.css
  src/components/MissionArea/MissionArea.js
  src/components/MissionArea/MissionArea.test.js
  src/components/StoryArea/Story.test.js
  src/components/StoryArea/StoryArea.css
  src/components/StoryArea/StoryArea.js
Labels: testing

#36 Thunk testing
  package-lock.json
  package.json
  src/components/IDPage/IDPage.js
  src/components/IDPage/IDPage.test.js
  src/thunks/fetchCountries.js
  src/thunks/fetchCountries.test.js
Labels: redux, testing

#37 Minor Css changes
  src/components/IDPage/IDPage.css
  src/components/IDPage/IDPage.js
  src/components/MissionArea/MissionArea.css
  src/components/MissionArea/MissionArea.js
  src/components/StoryArea/StoryArea.css
  src/components/StoryArea/StoryArea.js
Labels: css

#38 Actions testing
  src/actions/addID.test.js
  src/actions/hasErrored.test.js
  src/actions/isLoading.test.js
  src/actions/setCountries.test.js
Labels: testing

#40 Reducer testing tj
  src/reducers/addIDReducer.test.js
  src/reducers/countriesReducer.test.js
  src/reducers/hasErroredReducer.test.js
  src/reducers/isLoadingReducer.test.js
Labels: testing

#45 Add should dispatch setCountries with the correct params test
  src/thunks/fetchCountries.test.js
Labels: testing

#46 Id page test
  src/components/IDPage/IDPage.js
  src/components/IDPage/IDPage.test.js
Labels: redux, testing

#47 Id form test
  src/components/IDForm/IDForm.js
  src/components/IDForm/IDForm.test.js
  src/components/IDPage/IDPage.test.js
Labels: testing

#49 App integration tests
  src/components/App/App.test.js
  src/components/IDForm/IDForm.js
  src/components/IDForm/IDForm.test.js
  src/components/Identity/Identity.js
Labels: testing
